In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [13]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15000001,Williams,443,France,Male,55,10,7280.55,1,0,1,115068.83,0
1,2,15000002,Smith,677,France,Female,28,9,61370.20,1,0,1,138467.04,1
2,3,15000003,Jones,509,Germany,Female,69,2,8243.57,1,1,0,136030.62,1
3,4,15000004,Smith,739,Spain,Female,65,8,158824.07,1,0,1,68617.01,0
4,5,15000005,Martinez a,571,France,Male,70,1,96794.53,3,1,1,17723.99,1

In [14]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, errors='ignore')
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,443,France,Male,55,10,7280.55,1,0,1,115068.83,0
1,677,France,Female,28,9,61370.20,1,0,1,138467.04,1
2,509,Germany,Female,69,2,8243.57,1,1,0,136030.62,1
3,739,Spain,Female,65,8,158824.07,1,0,1,68617.01,0
4,571,France,Male,70,1,96794.53,3,1,1,17723.99,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,826,Germany,Male,27,4,75105.82,3,0,0,115602.78,1
9996,584,Spain,Female,63,3,156437.13,1,0,0,131128.30,1
9997,692,Spain,Male,58,0,142004.29,3,1,1,28365.13,0
9998,605,Germany,Female,41,3,121921.46,4,1,0,110719.65,0
9999,814,Germany,Male,59,7,116274.59,3,0,1,45981.53,1

In [15]:
label_encoder_gender=LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,443,France,1,55,10,7280.55,1,0,1,115068.83,0
1,677,France,0,28,9,61370.20,1,0,1,138467.04,1
2,509,Germany,0,69,2,8243.57,1,1,0,136030.62,1
3,739,Spain,0,65,8,158824.07,1,0,1,68617.01,0
4,571,France,1,70,1,96794.53,3,1,1,17723.99,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,826,Germany,1,27,4,75105.82,3,0,0,115602.78,1
9996,584,Spain,0,63,3,156437.13,1,0,0,131128.30,1
9997,692,Spain,1,58,0,142004.29,3,1,1,28365.13,0
9998,605,Germany,0,41,3,121921.46,4,1,0,110719.65,0
9999,814,Germany,1,59,7,116274.59,3,0,1,45981.53,1

In [16]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [17]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [18]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  1.0                0.0              0.0
2                  0.0                1.0              0.0
3                  0.0                0.0              1.0
4                  1.0                0.0              0.0
...                ...                ...              ...
9995               0.0                1.0              0.0
9996               0.0                0.0              1.0
9997               0.0                0.0              1.0
9998               0.0                1.0              0.0
9999               0.0                1.0              0.0

[10000 rows x 3 columns]

In [19]:
data = pd.concat([data.drop(['Geography'], axis=1), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,443,1,55,10,7280.55,1,0,1,115068.83,0,1.0,0.0,0.0
1,677,0,28,9,61370.20,1,0,1,138467.04,1,1.0,0.0,0.0
2,509,0,69,2,8243.57,1,1,0,136030.62,1,0.0,1.0,0.0
3,739,0,65,8,158824.07,1,0,1,68617.01,0,0.0,0.0,1.0
4,571,1,70,1,96794.53,3,1,1,17723.99,1,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,826,1,27,4,75105.82,3,0,0,115602.78,1,0.0,1.0,0.0
9996,584,0,63,3,156437.13,1,0,0,131128.30,1,0.0,0.0,1.0
9997,692,1,58,0,142004.29,3,1,1,28365.13,0,0.0,0.0,1.0
9998,605,0,41,3,121921.46,4,1,0,110719.65,0,0.0,1.0,0.0
9999,814,1,59,7,116274.59,3,0,1,45981.53,1,0.0,1.0,0.0

In [20]:
import pickle
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [21]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,443,1,55,10,7280.55,1,0,1,115068.83,0,1.0,0.0,0.0
1,677,0,28,9,61370.20,1,0,1,138467.04,1,1.0,0.0,0.0
2,509,0,69,2,8243.57,1,1,0,136030.62,1,0.0,1.0,0.0
3,739,0,65,8,158824.07,1,0,1,68617.01,0,0.0,0.0,1.0
4,571,1,70,1,96794.53,3,1,1,17723.99,1,1.0,0.0,0.0

In [22]:
X = data.drop('Exited', axis=1)
Y = data['Exited']
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,443,1,55,10,7280.55,1,0,1,115068.83,0,1.0,0.0,0.0
1,677,0,28,9,61370.20,1,0,1,138467.04,1,1.0,0.0,0.0
2,509,0,69,2,8243.57,1,1,0,136030.62,1,0.0,1.0,0.0
3,739,0,65,8,158824.07,1,0,1,68617.01,0,0.0,0.0,1.0
4,571,1,70,1,96794.53,3,1,1,17723.99,1,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,826,1,27,4,75105.82,3,0,0,115602.78,1,0.0,1.0,0.0
9996,584,0,63,3,156437.13,1,0,0,131128.30,1,0.0,0.0,1.0
9997,692,1,58,0,142004.29,3,1,1,28365.13,0,0.0,0.0,1.0
9998,605,0,41,3,121921.46,4,1,0,110719.65,0,0.0,1.0,0.0
9999,814,1,59,7,116274.59,3,0,1,45981.53,1,0.0,1.0,0.0

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
X_train

array([[ 1.32151565, -0.99476371, -1.11878764, ..., -0.71874034,
         1.4010578 , -0.68895165],
       [ 1.59947145,  1.00526385,  0.38879157, ..., -0.71874034,
        -0.71374643,  1.45148066],
       [ 1.30066897, -0.99476371, -1.51206917, ..., -0.71874034,
        -0.71374643,  1.45148066],
       ...,
       [ 0.17494799, -0.99476371, -1.64316301, ..., -0.71874034,
        -0.71374643,  1.45148066],
       [ 0.55018831, -0.99476371,  1.43754232, ..., -0.71874034,
         1.4010578 , -0.68895165],
       [ 0.35561925,  1.00526385, -0.46331842, ...,  1.39132305,
        -0.71374643, -0.68895165]], shape=(8000, 12))

In [25]:
with open ('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [26]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,443,1,55,10,7280.55,1,0,1,115068.83,0,1.0,0.0,0.0
1,677,0,28,9,61370.20,1,0,1,138467.04,1,1.0,0.0,0.0
2,509,0,69,2,8243.57,1,1,0,136030.62,1,0.0,1.0,0.0
3,739,0,65,8,158824.07,1,0,1,68617.01,0,0.0,0.0,1.0
4,571,1,70,1,96794.53,3,1,1,17723.99,1,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,826,1,27,4,75105.82,3,0,0,115602.78,1,0.0,1.0,0.0
9996,584,0,63,3,156437.13,1,0,0,131128.30,1,0.0,0.0,1.0
9997,692,1,58,0,142004.29,3,1,1,28365.13,0,0.0,0.0,1.0
9998,605,0,41,3,121921.46,4,1,0,110719.65,0,0.0,1.0,0.0
9999,814,1,59,7,116274.59,3,0,1,45981.53,1,0.0,1.0,0.0

ANN IMPLEMENTATION

In [27]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [28]:
# To fix the NameError, execute the cells that define X_train (e.g., cell 11) before running this cell.
# X_train.shape[1]

In [29]:
## Build ANN Model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

c:\Users\rajes\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [32]:
import tensorflow


opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [33]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [34]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [35]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
early_stopping_callback

In [36]:
%pip install tensorboard

Requirement already satisfied: tensorboard in c:\Users\rajes\miniconda3\Lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (2.4.4)
Requirement already satisfied: packaging in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (12.2.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (7.34.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (80.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\Users\rajes\miniconda3\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in c:\Users\rajes\miniconda3\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in c:\Users\rajes\miniconda3\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [37]:
history = model.fit(
    X_train,
    Y_train,
    validation_data=(X_test, Y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping_callback, tensorboard_callback]
    )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4995 - loss: 0.6992 - val_accuracy: 0.5150 - val_loss: 0.6928
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5311 - loss: 0.6917 - val_accuracy: 0.5060 - val_loss: 0.7001
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5359 - loss: 0.6889 - val_accuracy: 0.5220 - val_loss: 0.6925
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5429 - loss: 0.6874 - val_accuracy: 0.5255 - val_loss: 0.6933
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5499 - loss: 0.6850 - val_accuracy: 0.5145 - val_loss: 0.6956
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5580 - loss: 0.6833 - val_accuracy: 0.5160 - val_loss: 0.6952
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5598 - loss: 0.6810 - val_accuracy: 0.5165 - val_loss: 0.6951
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5684 - loss: 0.6800 - val_accuracy: 0.5200 - val_loss: 0.6988
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5700 - loss: 0.6777 - val_accuracy: 0.5285 - val_loss: 0.6976
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5784 - loss: 0.6755 - val_accuracy: 0.5090 - val_loss: 0.7007
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5857 - loss: 0.6731 - val_accuracy: 0.5130 - val_loss: 0.7021
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5882 - loss: 0.6712 - val_accuracy: 0.5110 - val_loss: 0.7003
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5901 - loss: 0.6688 - val_accuracy: 0.5070 - val_loss: 0.7057

In [38]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [42]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [48]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 15508), started 4:07:45 ago. (Use '!kill 15508' to kill it.)